// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'hb-focus-link': string;

  'hb-grid-actions': string;

  'hb-grid-featured': string;

  'hb-grid-mosaic': string;

  'hb-homepage-link': string;

  'hb-homepage-main': string;

  'hb-homepage-shell': string;

  'hb-layout-tier-marker': string;

  'hb-responsive-grid': string;

}

declare const strings: IExportStyles;

export default strings;